import { FinanceState } from '../models/finance.model';

import { DEMO_ORGANIZATION_ID } from '../../../core/seed/ids';

const ORG = DEMO_ORGANIZATION_ID;

export function createInitialFinanceState(): FinanceState {
  return {
    products: [
      {
        id: 'prd-001',
        organizationId: ORG,
        name: 'Electric Scooter Model A',
        vinNumber: 'MD2A11BX1P1234567',
        model: 'Model A',
        batteryType: 'Lithium 2.5 kWh',
        bodyColor: 'Gloss White',
        status: 'active',
        createdAt: '2026-01-08',
      },
      {
        id: 'prd-002',
        organizationId: ORG,
        name: 'Electric Scooter Model B',
        vinNumber: 'MD2B22CX8P7654321',
        model: 'Model B',
        batteryType: 'Lithium 3.2 kWh',
        bodyColor: 'Matte Grey',
        status: 'active',
        createdAt: '2026-02-14',
      },
      {
        id: 'prd-003',
        organizationId: ORG,
        name: 'Service Plan Annual',
        vinNumber: '',
        model: '',
        batteryType: '',
        bodyColor: '',
        status: 'active',
        createdAt: '2026-03-01',
      },
    ],
    categories: [
      { id: 'cat-001', organizationId: ORG, name: 'Procurement', description: 'Parts and materials', isActive: true, createdAt: '2026-01-05' },
      { id: 'cat-002', organizationId: ORG, name: 'Operations', description: 'Day-to-day operating spend', isActive: true, createdAt: '2026-01-05' },
      { id: 'cat-003', organizationId: ORG, name: 'Maintenance', description: 'Workshop and repairs', isActive: true, createdAt: '2026-01-05' },
      { id: 'cat-004', organizationId: ORG, name: 'Logistics', description: 'Freight and handling', isActive: true, createdAt: '2026-01-05' },
      { id: 'cat-005', organizationId: ORG, name: 'Other', description: 'Unclassified spend', isActive: true, createdAt: '2026-01-05' },
    ],
    subcategories: [
      { id: 'sub-001', organizationId: ORG, categoryId: 'cat-001', categoryName: 'Procurement', name: 'Batteries', description: '', isActive: true, createdAt: '2026-01-06' },
      { id: 'sub-002', organizationId: ORG, categoryId: 'cat-003', categoryName: 'Maintenance', name: 'Workshop parts', description: '', isActive: true, createdAt: '2026-01-06' },
      { id: 'sub-003', organizationId: ORG, categoryId: 'cat-004', categoryName: 'Logistics', name: 'Freight', description: '', isActive: true, createdAt: '2026-01-06' },
    ],
    offerings: [
      {
        id: 'off-001',
        organizationId: ORG,
        productId: 'prd-003',
        productName: 'Service Plan Annual',
        name: 'Service Plan Annual',
        description: 'Annual maintenance offering',
        amount: '56000.00',
        isActive: true,
        createdAt: '2026-03-02',
      },
      {
        id: 'off-002',
        organizationId: ORG,
        productId: 'prd-001',
        productName: 'Electric Scooter Model A',
        name: 'Workshop booking — Model A',
        description: 'Workshop slot for Model A',
        amount: '8500.00',
        isActive: true,
        createdAt: '2026-04-01',
      },
    ],
    expenses: [
      {
        id: 'exp-1042',
        organizationId: ORG,
        vendorId: 'vnd-001',
        vendorName: 'Metro Supplies Ltd',
        categoryId: 'cat-001',
        categoryName: 'Procurement',
        subcategoryId: 'sub-001',
        subcategoryName: 'Batteries',
        productId: 'prd-001',
        productName: 'Electric Scooter Model A',
        productServiceName: 'Battery pack',
        sku: 'BAT-A-25',
        quantity: '2.00',
        unitPrice: '12250.00',
        cost: '24500.00',
        gstPercentage: '18.00',
        gstAmount: '4410.00',
        purchaseOrderNumber: 'PO-2026-014',
        expenseDate: '2026-08-24',
        enteredBy: 'System Administrator',
        status: 'approved',
        createdAt: '2026-08-24',
      },
      {
        id: 'exp-1041',
        organizationId: ORG,
        vendorId: 'vnd-002',
        vendorName: 'TechParts India',
        categoryId: 'cat-003',
        categoryName: 'Maintenance',
        subcategoryId: 'sub-002',
        subcategoryName: 'Workshop parts',
        productId: 'prd-002',
        productName: 'Electric Scooter Model B',
        productServiceName: 'Controller board',
        sku: 'CTL-B-01',
        quantity: '1.00',
        unitPrice: '12800.00',
        cost: '12800.00',
        gstPercentage: '18.00',
        gstAmount: '2304.00',
        purchaseOrderNumber: '',
        expenseDate: '2026-08-23',
        enteredBy: 'System Administrator',
        status: 'pending',
        createdAt: '2026-08-23',
      },
      {
        id: 'exp-1040',
        organizationId: ORG,
        vendorId: 'vnd-003',
        vendorName: 'National Logistics',
        categoryId: 'cat-004',
        categoryName: 'Logistics',
        subcategoryId: 'sub-003',
        subcategoryName: 'Freight',
        productId: null,
        productName: '',
        productServiceName: 'Inbound freight',
        sku: '',
        quantity: '1.00',
        unitPrice: '18650.00',
        cost: '18650.00',
        gstPercentage: '12.00',
        gstAmount: '2238.00',
        purchaseOrderNumber: '',
        expenseDate: '2026-08-22',
        enteredBy: 'System Administrator',
        status: 'approved',
        createdAt: '2026-08-22',
      },
    ],
    accounts: [
      {
        id: 'acc-001',
        organizationId: ORG,
        name: 'Main Operating Account',
        accountType: 'bank',
        accountNumber: 'XXXX4521',
        balance: '312400.00',
        isActive: true,
        createdAt: '2026-01-02',
      },
      {
        id: 'acc-002',
        organizationId: ORG,
        name: 'Petty Cash',
        accountType: 'cash',
        accountNumber: '',
        balance: '45800.00',
        isActive: true,
        createdAt: '2026-01-02',
      },
      {
        id: 'acc-003',
        organizationId: ORG,
        name: 'GST Settlement Account',
        accountType: 'bank',
        accountNumber: 'XXXX8890',
        balance: '129000.00',
        isActive: true,
        createdAt: '2026-01-02',
      },
    ],
    transactions: [
      {
        id: 'txn-001',
        organizationId: ORG,
        accountId: 'acc-001',
        accountName: 'Main Operating Account',
        transactionType: 'credit',
        amount: '40000.00',
        referenceType: 'receipt',
        referenceId: 'rcp-001',
        description: 'Collection SI-2026-0892 (posted manually)',
        transactionDate: '2026-08-24',
        reconciled: true,
        createdAt: '2026-08-24',
      },
      {
        id: 'txn-002',
        organizationId: ORG,
        accountId: 'acc-001',
        accountName: 'Main Operating Account',
        transactionType: 'debit',
        amount: '24500.00',
        referenceType: 'expense',
        referenceId: 'exp-1042',
        description: 'Metro Supplies battery packs',
        transactionDate: '2026-08-24',
        reconciled: false,
        createdAt: '2026-08-24',
      },
      {
        id: 'txn-003',
        organizationId: ORG,
        accountId: 'acc-002',
        accountName: 'Petty Cash',
        transactionType: 'debit',
        amount: '1200.00',
        referenceType: '',
        referenceId: '',
        description: 'Workshop consumables',
        transactionDate: '2026-08-20',
        reconciled: true,
        createdAt: '2026-08-20',
      },
    ],
    documents: [
      {
        id: 'doc-001',
        organizationId: ORG,
        entityName: 'expense',
        entityId: 'exp-1042',
        fileName: 'metro-invoice-24500.pdf',
        mimeType: 'application/pdf',
        fileSize: '180 KB',
        storageKey: `${ORG}/expenses/exp-1042/metro-invoice-24500.pdf`,
        uploadedBy: 'System Administrator',
        createdAt: '2026-08-24',
      },
    ],
    auditEntries: [
      {
        id: 'aud-001',
        organizationId: ORG,
        action: 'create',
        entityName: 'expense',
        entityId: 'exp-1042',
        summary: 'Recorded expense EXP-1042 for Metro Supplies Ltd',
        createdAt: '2026-08-24',
      },
      {
        id: 'aud-002',
        organizationId: ORG,
        action: 'create',
        entityName: 'finance_transaction',
        entityId: 'txn-001',
        summary: 'Posted credit 40000.00 to Main Operating Account',
        createdAt: '2026-08-24',
      },
    ],
  };
}
