import { O2cState } from '../models/o2c.model';

import { DEMO_ORGANIZATION_ID } from '../../../core/seed/ids';

const ORG = DEMO_ORGANIZATION_ID;

export function createInitialO2cState(): O2cState {
  return {
    customers: [
      {
        id: 'cus-001',
        organizationId: ORG,
        name: 'Acme Retail Pvt Ltd',
        address: '14 MG Road, Bengaluru',
        createdAt: '2026-03-02',
        gstin: null,
        state: null,
        creditLimit: null,
        addressProofName: 'acme-address-proof.pdf',
        addressProofSize: '240 KB',
        addressProofType: 'application/pdf',
      },
      {
        id: 'cus-002',
        organizationId: ORG,
        name: 'Greenfield Motors',
        address: 'Plot 9, Hinjewadi, Pune',
        createdAt: '2026-04-18',
        gstin: null,
        state: null,
        creditLimit: null,
        addressProofName: '',
        addressProofSize: '',
        addressProofType: '',
      },
      {
        id: 'cus-003',
        organizationId: ORG,
        name: 'Horizon Fleet',
        address: 'Dock 2, Nhava Sheva',
        createdAt: '2026-06-01',
        gstin: null,
        state: null,
        creditLimit: null,
        addressProofName: 'horizon-utility-bill.pdf',
        addressProofSize: '180 KB',
        addressProofType: 'application/pdf',
      },
    ],
    offerings: [
      { id: 'off-001', name: 'Service Plan Annual' },
      { id: 'off-002', name: 'Workshop booking — Model A' },
    ],
    plans: [
      { id: 'pln-001', name: 'Annual maintenance', amount: '56000.00' },
      { id: 'pln-002', name: 'Fleet retainer', amount: '142000.00' },
    ],
    quotations: [
      {
        id: 'qt-001',
        organizationId: ORG,
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        quoteNumber: 'Q-2026-012',
        status: 'converted',
        quoteDate: '2026-08-08',
        validUntil: '2026-08-22',
        totalAmount: '78500.00',
        createdAt: '2026-08-08',
      },
      {
        id: 'qt-002',
        organizationId: ORG,
        customerId: 'cus-002',
        customerName: 'Greenfield Motors',
        quoteNumber: 'Q-2026-013',
        status: 'sent',
        quoteDate: '2026-08-20',
        validUntil: '2026-09-03',
        totalAmount: '142000.00',
        createdAt: '2026-08-20',
      },
    ],
    salesOrders: [
      {
        id: 'so-001',
        organizationId: ORG,
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        quotationId: 'qt-001',
        quoteNumber: 'Q-2026-012',
        orderNumber: 'SO-2026-008',
        status: 'fulfilled',
        orderDate: '2026-08-10',
        totalAmount: '78500.00',
        createdAt: '2026-08-10',
      },
    ],
    deliveries: [
      {
        id: 'dn-001',
        organizationId: ORG,
        salesOrderId: 'so-001',
        orderNumber: 'SO-2026-008',
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        deliveryNumber: 'DN-2026-005',
        status: 'delivered',
        deliveryDate: '2026-08-14',
        createdAt: '2026-08-14',
      },
    ],
    salesInvoices: [
      {
        id: 'sinv-001',
        organizationId: ORG,
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        salesOrderId: 'so-001',
        orderNumber: 'SO-2026-008',
        deliveryId: 'dn-001',
        deliveryNumber: 'DN-2026-005',
        invoiceNumber: 'O2C-2026-0892',
        status: 'partially_paid',
        approvalStatus: 'approved',
        invoiceDate: '2026-08-15',
        amount: '78500.00',
        gstAmount: '14130.00',
        createdAt: '2026-08-15',
      },
    ],
    collections: [
      {
        id: 'col-001',
        organizationId: ORG,
        salesInvoiceId: 'sinv-001',
        invoiceNumber: 'O2C-2026-0892',
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        collectionDate: '2026-08-24',
        amount: '40000.00',
        paymentMode: 'UPI',
        status: 'completed',
        createdAt: '2026-08-24',
      },
    ],
    receivables: [
      {
        id: 'ar-001',
        organizationId: ORG,
        sourceType: 'sales_invoice',
        sourceId: 'sinv-001',
        invoiceNumber: 'O2C-2026-0892',
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        amount: '78500.00',
        outstanding: '38500.00',
        dueDate: '2026-09-14',
        status: 'partial',
        createdAt: '2026-08-15',
      },
    ],
    bookings: [
      {
        id: 'bk-001',
        organizationId: ORG,
        offeringId: 'off-001',
        offeringName: 'Service Plan Annual',
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        bookingStartDate: '2026-08-01',
        bookingEndDate: '2027-07-31',
        securityPaid: '10000.00',
        createdAt: '2026-07-28',
      },
    ],
    invoices: [
      {
        id: 'inv-001',
        organizationId: ORG,
        invoiceNumber: 'SI-2026-0892',
        customerId: 'cus-001',
        customerName: 'Acme Retail Pvt Ltd',
        bookingId: 'bk-001',
        bookingLabel: 'BK-2026-001',
        planId: 'pln-001',
        planName: 'Annual maintenance',
        invoiceRaisedDate: '2026-08-22',
        securityAmountDeposited: '10000.00',
        invoiceAmount: '78500.00',
        isGstInvoice: true,
        gstAmount: '14130.00',
        status: 'partially_paid',
        createdAt: '2026-08-22',
      },
    ],
    receipts: [
      {
        id: 'rcp-001',
        organizationId: ORG,
        invoiceId: 'inv-001',
        invoiceNumber: 'SI-2026-0892',
        receiptDate: '2026-08-24',
        receiptAmount: '40000.00',
        pendingAmount: '38500.00',
        paymentMode: 'UPI',
        transactionLast4: '4821',
        enteredBy: 'System Administrator',
        createdAt: '2026-08-24',
      },
    ],
  };
}
